---
- name: Check Available Updates (RHEL)
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather updates
      ansible.builtin.yum:
        list: updates
      register: available_updates

    - name: List updates
      debug:
        msg: "{{ item.key }} is available in version {{ item.value.version }}"
      loop: "{{ available_updates.results | dict2items }}"
